name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Build
          files: "**/*.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
